using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Common.Mod.Common.Config;
using Common.Mod.Generator.Utils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Common.Mod.Generator.Generators;

[Generator]
public class ConfigGenerator : IIncrementalGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() }
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pipeline = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".json"))
            .Select(static (text, cancellationToken) =>
            {
                var name = Path.GetFileNameWithoutExtension(text.Path);
                var spec = JsonSerializer.Deserialize<RootConfigSpec>(
                    json: text.GetText(cancellationToken)?.ToString() ?? throw new InvalidOperationException(),
                    options: JsonOptions
                );

                return new KeyValuePair<string, RootConfigSpec?>(name, spec);
            });

        context.RegisterSourceOutput(pipeline, Execute);
    }

    private static void Execute(SourceProductionContext context, KeyValuePair<string, RootConfigSpec?> pair)
    {
        ValidateSpec(pair.Value);

        var name = pair.Key;
        var spec = pair.Value!;

        var sourceBuilder = new IndentedStringBuilder();
        sourceBuilder.Append($"""
                              // This file was autogenerated by Common.Mod.Generator. DO NOT MODIFY!

                              #nullable enable

                              namespace {spec.ClassNamespace};

                              """);

        // Nestable configs
        foreach (var nestableSpec in spec.Nestable)
        {
            AppendConfig(sourceBuilder, nestableSpec);
        }

        // Root config
        AppendConfig(
            sourceBuilder: sourceBuilder,
            spec: spec,
            inheritFrom: "Common.Config.IRootConfig",
            additionalData: innerSourceBuilder =>
            {
                // IRootConfig implementation
                innerSourceBuilder.AppendLine("");
                innerSourceBuilder.AppendLine("#region IRootConfig");
                innerSourceBuilder.AppendLine("");
                innerSourceBuilder.AppendLine($"public string Version() => \"{spec.Version}\";");
                innerSourceBuilder.AppendLine("");
                innerSourceBuilder.AppendLine("#endregion IRootConfig");
            }
        );

        context.AddSource($"{name}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    private static void ValidateSpec(RootConfigSpec? spec)
    {
        ThrowIf(() => spec is null);

        ThrowIf(() => string.IsNullOrWhiteSpace(spec!.ClassName));
        ThrowIf(() => string.IsNullOrWhiteSpace(spec!.ClassNamespace));
        ThrowIf(() => string.IsNullOrWhiteSpace(spec!.Version));

        ThrowIf(() => spec!.Entries.IsDefaultOrEmpty);
        foreach (var entrySpec in spec!.Entries)
        {
            ThrowIf(() => string.IsNullOrWhiteSpace(entrySpec.Name));
            ThrowIf(() => entrySpec.Type == ConfigEntryTypeSpec.Nested && string.IsNullOrWhiteSpace(entrySpec.Nested));
        }
    }

    private static void ThrowIf(Func<bool> predicate)
    {
        if (predicate.Invoke())
        {
            throw new InvalidOperationException();
        }
    }

    private static void AppendConfig(
        IndentedStringBuilder sourceBuilder,
        ConfigSpec spec,
        string? inheritFrom = null,
        Action<IndentedStringBuilder>? additionalData = null
    )
    {
        if (!string.IsNullOrWhiteSpace(spec.Description))
        {
            sourceBuilder.AppendLines(
                $"""

                 /// <summary>
                 /// {spec.Description}
                 /// </summary>
                 """
            );
        }

        var declarationBuilder = new StringBuilder("internal class ");
        declarationBuilder.Append(spec.ClassName);
        if (inheritFrom is not null)
        {
            declarationBuilder.Append(" : ");
            declarationBuilder.Append(inheritFrom);
        }

        sourceBuilder.AppendLines(declarationBuilder.ToString());
        sourceBuilder.AppendLines("{");
        sourceBuilder.IncrementIndent();

        // Entries
        {
            sourceBuilder.AppendLine("#region Entries");
            sourceBuilder.AppendLine("");

            foreach (var entrySpec in spec.Entries)
            {
                AppendEntry(sourceBuilder, entrySpec);
            }

            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("#endregion Entries");
        }

        // Additional data
        additionalData?.Invoke(sourceBuilder);

        sourceBuilder.DecrementIndent();
        sourceBuilder.AppendLine("}");
    }

    private static void AppendEntry(IndentedStringBuilder sourceBuilder, ConfigEntrySpec spec)
    {
        string type;
        var nullable = spec.Nullable;
        var defaultValueBuilder = new StringBuilder(" = ");

        // Type
        {
            switch (spec.Type)
            {
                case ConfigEntryTypeSpec.Bool:
                    type = nullable ? "bool?" : "bool";
                    break;

                case ConfigEntryTypeSpec.Int:
                    type = nullable ? "int?" : "int";
                    break;

                case ConfigEntryTypeSpec.UInt:
                    type = nullable ? "uint?" : "uint";
                    break;

                case ConfigEntryTypeSpec.Float:
                    type = nullable ? "float?" : "float";
                    break;

                case ConfigEntryTypeSpec.String:
                    type = "string?";
                    nullable = true;
                    break;

                case ConfigEntryTypeSpec.Nested:
                    type = $"{spec.Nested!}?";
                    nullable = true;
                    break;

                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        // Default value
        {
            if (spec.Type is not ConfigEntryTypeSpec.Nested && (spec.DefaultValue is not null || nullable))
            {
                defaultValueBuilder.Append(JsonSerializer.Serialize(spec.DefaultValue, JsonOptions));
            }
            else
            {
                defaultValueBuilder.Append("default");
            }

            if (spec is { DefaultValue: not null, Type: ConfigEntryTypeSpec.Float })
            {
                defaultValueBuilder.Append('f');
            }

            defaultValueBuilder.Append(';');
        }

        if (!string.IsNullOrWhiteSpace(spec.Description))
        {
            sourceBuilder.AppendLines(
                $"""

                 /// <summary>
                 /// {spec.Description}
                 /// </summary>
                 """
            );
        }

        sourceBuilder.AppendLine($"public {type} {spec.Name} {{ get; set; }}{defaultValueBuilder}");
    }
}
