using System;
using System.Text;
using System.Text.Json;
using Common.Mod.Generator.Specs;
using Common.Mod.Generator.Utils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Common.Mod.Generator.Generators;

[Generator]
public class ConfigPacketGenerator : Generator, IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pipeline = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".json"))
            .Select(static (text, cancellationToken) => JsonSerializer.Deserialize<RootConfigSpec>(
                json: text.GetText(cancellationToken)?.ToString() ?? throw new InvalidOperationException(),
                options: JsonOptions
            ));

        context.RegisterSourceOutput(pipeline, Execute);
    }

    private static void Execute(SourceProductionContext context, RootConfigSpec? spec)
    {
        ValidateSpec(spec);

        if (!spec!.Synchronize)
        {
            // This config isn't synchronized, thus a packet isn't needed.
            return;
        }

        var sourceBuilder = new IndentedStringBuilder();
        sourceBuilder.Append($"""
                              // This file was autogenerated by Common.Mod.Generator. DO NOT MODIFY!

                              #nullable enable

                              using ProtoBuf;

                              namespace {spec.ClassNamespace};

                              """);

        // Nestable configs
        foreach (var nestableSpec in spec.Nestable)
        {
            AppendConfig(sourceBuilder, nestableSpec);
        }

        // Root config
        AppendConfig(sourceBuilder, spec);

        context.AddSource($"{spec.ClassName}Packet.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    private static void AppendConfig(IndentedStringBuilder sourceBuilder, ConfigSpec spec)
    {
        sourceBuilder.AppendLine("");
        sourceBuilder.AppendLine("[ProtoContract(ImplicitFields = ImplicitFields.AllPublic)]");

        // Class declaration
        sourceBuilder.AppendLine($"public class {spec.ClassName}Packet");
        sourceBuilder.AppendLine("{");
        sourceBuilder.IncrementIndent();

        // Entries
        {
            sourceBuilder.AppendLine("#region Entries");
            sourceBuilder.AppendLine("");

            foreach (var entrySpec in spec.Entries)
            {
                AppendConfigEntry(
                    sourceBuilder: sourceBuilder,
                    spec: entrySpec,
                    nestedTypeSuffix: "Packet",
                    omitDescriptions: true
                );
            }

            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("#endregion Entries");
        }

        // Close class body
        sourceBuilder.DecrementIndent();
        sourceBuilder.AppendLine("}");
    }
}
