using System;
using System.Text;
using System.Text.Json;
using Common.Mod.Generator.Specs;
using Common.Mod.Generator.Utils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Common.Mod.Generator.Generators;

[Generator]
public class ConfigGenerator : Generator, IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pipeline = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".json"))
            .Select(static (text, cancellationToken) => JsonSerializer.Deserialize<RootConfigSpec>(
                json: text.GetText(cancellationToken)?.ToString() ?? throw new InvalidOperationException(),
                options: JsonOptions
            ));

        context.RegisterSourceOutput(pipeline, Execute);
    }

    private static void Execute(SourceProductionContext context, RootConfigSpec? spec)
    {
        ValidateSpec(spec);

        var sourceBuilder = new IndentedStringBuilder();
        sourceBuilder.Append($"""
                              // This file was autogenerated by Common.Mod.Generator. DO NOT MODIFY!

                              #nullable enable

                              namespace {spec!.ClassNamespace};

                              """);

        // Nestable configs
        foreach (var nestableSpec in spec.Nestable)
        {
            AppendConfig(sourceBuilder, spec, nestableSpec);
        }

        // Root config
        AppendConfig(
            sourceBuilder: sourceBuilder,
            rootSpec: spec,
            spec: spec,
            inheritFrom: "Common.Config.IRootConfig",
            additionalData: innerSourceBuilder =>
            {
                // IRootConfig implementation
                {
                    innerSourceBuilder.AppendLine("");
                    innerSourceBuilder.AppendLine("#region IRootConfig");
                    innerSourceBuilder.AppendLine("");
                    innerSourceBuilder.AppendLine($"public string Version() => \"{spec.Version}\";");
                    innerSourceBuilder.AppendLine("");
                    innerSourceBuilder.AppendLine("#endregion IRootConfig");
                }
            }
        );

        context.AddSource($"{spec.ClassName}.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
    }

    private static void AppendConfig(
        IndentedStringBuilder sourceBuilder,
        RootConfigSpec rootSpec,
        ConfigSpec spec,
        string? inheritFrom = null,
        Action<IndentedStringBuilder>? additionalData = null
    )
    {
        // Class description
        if (!string.IsNullOrWhiteSpace(spec.Description))
        {
            sourceBuilder.AppendLines(
                $"""

                 /// <summary>
                 /// {spec.Description}
                 /// </summary>
                 """
            );
        }

        // Class declaration
        var declarationBuilder = new StringBuilder("public class ");
        declarationBuilder.Append(spec.ClassName);
        declarationBuilder.Append(" : Common.Config.IConfig");

        if (rootSpec.Synchronize)
        {
            declarationBuilder.Append("<");
            declarationBuilder.Append(spec.ClassName);
            declarationBuilder.Append("Packet>");
        }

        if (inheritFrom is not null)
        {
            declarationBuilder.Append(", ");
            declarationBuilder.Append(inheritFrom);
        }

        sourceBuilder.AppendLines(declarationBuilder.ToString());
        sourceBuilder.AppendLine("{");
        sourceBuilder.IncrementIndent();

        // Entries
        {
            sourceBuilder.AppendLine("#region Entries");
            sourceBuilder.AppendLine("");

            foreach (var entrySpec in spec.Entries)
            {
                AppendConfigEntry(sourceBuilder, entrySpec);
            }

            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("#endregion Entries");
        }

        // IConfig implementation
        AppendIConfig(sourceBuilder, rootSpec, spec);

        // Additional data
        additionalData?.Invoke(sourceBuilder);

        // Close class body
        sourceBuilder.DecrementIndent();
        sourceBuilder.AppendLine("}");
    }

    private static void AppendIConfig(
        IndentedStringBuilder sourceBuilder,
        RootConfigSpec rootSpec,
        ConfigSpec spec
    )
    {
        sourceBuilder.AppendLine("");
        sourceBuilder.AppendLine("#region IConfig");
        sourceBuilder.AppendLine("");

        // IsSynchronized
        sourceBuilder.AppendLine($"public bool IsSynchronized() => {rootSpec.Synchronize.ToString().ToLowerInvariant()};");

        // ApplyPacket
        {
            sourceBuilder.AppendLine("");

            if (rootSpec.Synchronize)
            {
                sourceBuilder.AppendLine($"public void ApplyPacket({spec.ClassName}Packet packet)");
            }
            else
            {
                sourceBuilder.AppendLine("public void ApplyPacket(object packet)");
            }

            sourceBuilder.AppendLine("{");
            sourceBuilder.IncrementIndent();

            if (rootSpec.Synchronize)
            {
                foreach (var entrySpec in spec.Entries)
                {
                    if (entrySpec.Type == ConfigEntryTypeSpec.Nested)
                    {
                        sourceBuilder.AppendLine("");
                        sourceBuilder.AppendLine($"if (packet.{entrySpec.Name} is not null)");
                        sourceBuilder.AppendLine("{");
                        sourceBuilder.IncrementIndent();

                        sourceBuilder.AppendLine($"{entrySpec.Name}?.ApplyPacket(packet.{entrySpec.Name});");

                        sourceBuilder.DecrementIndent();
                        sourceBuilder.AppendLine("}");
                        sourceBuilder.AppendLine("else");
                        sourceBuilder.AppendLine("{");
                        sourceBuilder.IncrementIndent();

                        sourceBuilder.AppendLine($"{entrySpec.Name} = null;");

                        sourceBuilder.DecrementIndent();
                        sourceBuilder.AppendLine("}");
                        sourceBuilder.AppendLine("");
                        continue;
                    }

                    sourceBuilder.AppendLine($"{entrySpec.Name} = packet.{entrySpec.Name};");
                }
            }
            else
            {
                sourceBuilder.AppendLine("throw new NotImplementedException();");
            }

            sourceBuilder.DecrementIndent();
            sourceBuilder.AppendLine("}");
        }

        // CreatePacket
        {
            sourceBuilder.AppendLine("");

            if (rootSpec.Synchronize)
            {
                sourceBuilder.AppendLine($"public {spec.ClassName}Packet CreatePacket()");
            }
            else
            {
                sourceBuilder.AppendLine($"public object CreatePacket()");
            }

            sourceBuilder.AppendLine("{");
            sourceBuilder.IncrementIndent();

            if (rootSpec.Synchronize)
            {
                sourceBuilder.AppendLine($"return new {spec.ClassName}Packet");
                sourceBuilder.AppendLine("{");
                sourceBuilder.IncrementIndent();

                foreach (var entrySpec in spec.Entries)
                {
                    if (entrySpec.Type == ConfigEntryTypeSpec.Nested)
                    {
                        sourceBuilder.AppendLine($"{entrySpec.Name} = {entrySpec.Name}?.CreatePacket(),");
                        continue;
                    }

                    sourceBuilder.AppendLine($"{entrySpec.Name} = {entrySpec.Name},");
                }

                sourceBuilder.DecrementIndent();
                sourceBuilder.AppendLine("};");
            }
            else
            {
                sourceBuilder.AppendLine("throw new NotImplementedException();");
            }

            sourceBuilder.DecrementIndent();
            sourceBuilder.AppendLine("}");
        }

        sourceBuilder.AppendLine("");
        sourceBuilder.AppendLine("#endregion IConfig");
    }
}
