using System;
using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using CaseConverter;
using Common.Mod.Generator.Specs;
using Common.Mod.Generator.Utils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Common.Mod.Generator.Generators;

[Generator]
public class ConfigGenerator : IIncrementalGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() }
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pipeline = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".json"))
            .Select(static (text, cancellationToken) => JsonSerializer.Deserialize<ConfigDefinitionSpec>(
                json: text.GetText(cancellationToken)?.ToString() ?? throw new InvalidOperationException(),
                options: JsonOptions
            ));

        context.RegisterSourceOutput(pipeline, Execute);
    }

    private static void Execute(SourceProductionContext context, ConfigDefinitionSpec? spec)
    {
        ValidateSpec(spec);

        if (spec!.Configs is not null)
        {
            foreach (var configSpec in spec.Configs)
            {
                var source = GenerateConfig(configSpec);
                context.AddSource($"{configSpec.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        }

        foreach (var rootConfigSpec in spec.RootConfigs)
        {
            var source = GenerateConfig(rootConfigSpec);
            context.AddSource($"{rootConfigSpec.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateConfig(RootConfigSpec spec)
    {
        var sourceBuilder = new IndentedStringBuilder();

        sourceBuilder.AppendLine(GenerateClassHeader(spec));
        sourceBuilder.AppendLine($"public class {spec.ClassName} : IRootConfig");
        sourceBuilder.AppendLine("{");
        sourceBuilder.IncrementIndent();

        sourceBuilder.AppendLines(GenerateConfig(spec, skipClass: true));

        // IRootConfig implementation
        {
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("#region IRootConfig");
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine($"public string Version() => \"{spec.Version}\";");
            sourceBuilder.AppendLine($"public RootConfigType Type() => RootConfigType.{spec.Type};");
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("#endregion IRootConfig");
        }

        sourceBuilder.DecrementIndent();
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static string GenerateConfig(ConfigSpec spec, bool skipClass = false)
    {
        var sourceBuilder = new IndentedStringBuilder();

        if (!skipClass)
        {
            sourceBuilder.AppendLine(GenerateClassHeader(spec));
            sourceBuilder.AppendLine($"public class {spec.ClassName} : IConfig");
            sourceBuilder.AppendLine("{");
            sourceBuilder.IncrementIndent();
        }

        // Defaults
        {
            sourceBuilder.AppendLine($"private static readonly {spec.ClassName} Defaults = new();");
            sourceBuilder.AppendLine("");
        }

        sourceBuilder.AppendLines(GenerateFields(spec.Entries));
        sourceBuilder.AppendLines(GenerateProperties(spec.Entries));

        // IConfig implementation
        {
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("#region IConfig");
            sourceBuilder.AppendLine("");

            sourceBuilder.AppendLines(GenerateReset(spec.Entries));
            sourceBuilder.AppendLines(GenerateRender(spec.Entries));

            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("#endregion IConfig");
        }

        if (skipClass)
        {
            return sourceBuilder.ToString();
        }

        sourceBuilder.DecrementIndent();
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static string GenerateClassHeader(ConfigSpec spec)
    {
        var sourceBuilder = new StringBuilder($"""
                                               // This file was autogenerated by Common.Mod.Generator. DO NOT MODIFY!

                                               #nullable enable

                                               using Common.Mod.Common.Config;
                                               using Common.Mod.Config;

                                               namespace {spec.ClassNamespace};


                                               """);

        if (!string.IsNullOrWhiteSpace(spec.Description))
        {
            sourceBuilder.Append(
                $"""
                 /// <summary>
                 /// {spec.Description}
                 /// </summary>
                 """
            );
        }

        return sourceBuilder.ToString();
    }

    private static string GenerateFields(ImmutableArray<ConfigEntrySpec> specs)
    {
        var sourceBuilder = new StringBuilder("""
                                              #region Fields


                                              """);

        foreach (var spec in specs)
        {
            sourceBuilder.AppendLine($"private {GetType(spec)} _{spec.Name.ToCamelCase()} = {GetDefaultValue(spec)};");
        }

        sourceBuilder.Append("""

                             #endregion Fields
                             """);

        return sourceBuilder.ToString();
    }

    private static string GenerateProperties(ImmutableArray<ConfigEntrySpec> specs)
    {
        var sourceBuilder = new IndentedStringBuilder();
        sourceBuilder.Append("""

                             #region Properties


                             """);

        foreach (var spec in specs)
        {
            if (!string.IsNullOrWhiteSpace(spec.Description))
            {
                sourceBuilder.AppendLines(
                    $"""
                     /// <summary>
                     /// {spec.Description}
                     /// </summary>
                     """
                );
            }

            sourceBuilder.AppendLine($"public {GetType(spec)} {spec.Name.ToPascalCase()}");
            sourceBuilder.AppendLine("{");
            sourceBuilder.IncrementIndent();

            sourceBuilder.AppendLine($"get => _{spec.Name.ToCamelCase()};");
            sourceBuilder.AppendLine($"set => _{spec.Name.ToCamelCase()} = value;");

            sourceBuilder.DecrementIndent();
            sourceBuilder.AppendLine("}");
            sourceBuilder.AppendLine("");
        }

        sourceBuilder.AppendLine("#endregion Properties");

        return sourceBuilder.ToString();
    }

    private static string GenerateReset(ImmutableArray<ConfigEntrySpec> specs)
    {
        var sourceBuilder = new IndentedStringBuilder();

        sourceBuilder.AppendLine("public void Reset()");
        sourceBuilder.AppendLine("{");
        sourceBuilder.IncrementIndent();

        foreach (var spec in specs)
        {
            sourceBuilder.AppendLine($"_{spec.Name.ToCamelCase()} = Defaults._{spec.Name.ToCamelCase()};");
        }

        sourceBuilder.DecrementIndent();
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static string GenerateRender(ImmutableArray<ConfigEntrySpec> specs)
    {
        var sourceBuilder = new IndentedStringBuilder();

        sourceBuilder.AppendLine("");
        sourceBuilder.AppendLine("public void Render()");
        sourceBuilder.AppendLine("{");
        sourceBuilder.IncrementIndent();

        foreach (var spec in specs)
        {
            if (spec.Type is ConfigEntryTypeSpec.Nested)
            {
                sourceBuilder.AppendLine(
                    $"ConfigUI.{GetRenderer(spec)}(_{spec.Name.ToCamelCase()}, \"{spec.Name.ToCamelCase()}\", \"{spec.Label ?? spec.Name}\");");
                continue;
            }

            if (spec.Description is null)
            {
                sourceBuilder.AppendLine(
                    $"ConfigUI.{GetRenderer(spec)}(ref _{spec.Name.ToCamelCase()}, Defaults._{spec.Name.ToCamelCase()}, \"{spec.Name.ToCamelCase()}\", \"{spec.Label ?? spec.Name}\");");
            }
            else
            {
                sourceBuilder.AppendLine(
                    $"ConfigUI.{GetRenderer(spec)}(ref _{spec.Name.ToCamelCase()}, Defaults._{spec.Name.ToCamelCase()}, \"{spec.Name.ToCamelCase()}\", \"{spec.Label ?? spec.Name}\", \"{spec.Description}\");");
            }
        }

        sourceBuilder.DecrementIndent();
        sourceBuilder.AppendLine("}");

        return sourceBuilder.ToString();
    }

    private static string GetType(ConfigEntrySpec spec)
    {
        return spec.Type switch
        {
            ConfigEntryTypeSpec.Bool => "bool",
            ConfigEntryTypeSpec.Int32 => "int",
            ConfigEntryTypeSpec.Int64 => "long",
            ConfigEntryTypeSpec.UInt32 => "uint",
            ConfigEntryTypeSpec.UInt64 => "ulong",
            ConfigEntryTypeSpec.Float => "float",
            ConfigEntryTypeSpec.Double => "double",
            ConfigEntryTypeSpec.String => "string",
            ConfigEntryTypeSpec.Nested => $"{spec.Nested}",
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    private static string GetDefaultValue(ConfigEntrySpec spec)
    {
        if (spec.Type is ConfigEntryTypeSpec.Nested)
        {
            return "new()";
        }

        if (spec.DefaultValue is not null)
        {
            var defaultValue = JsonSerializer.Serialize(spec.DefaultValue, JsonOptions);
            return spec.Type switch
            {
                ConfigEntryTypeSpec.Float => $"{defaultValue}f",
                ConfigEntryTypeSpec.Double => $"{defaultValue}d",
                _ => defaultValue
            };
        }

        if (spec.Type is ConfigEntryTypeSpec.String)
        {
            return "string.Empty";
        }

        return "default";
    }

    private static string GetRenderer(ConfigEntrySpec spec)
    {
        return spec.Type switch
        {
            ConfigEntryTypeSpec.Bool => nameof(ConfigEntryTypeSpec.Bool),
            ConfigEntryTypeSpec.Int32 => nameof(ConfigEntryTypeSpec.Int32),
            ConfigEntryTypeSpec.Int64 => nameof(ConfigEntryTypeSpec.Int64),
            ConfigEntryTypeSpec.UInt32 => nameof(ConfigEntryTypeSpec.UInt32),
            ConfigEntryTypeSpec.UInt64 => nameof(ConfigEntryTypeSpec.UInt64),
            ConfigEntryTypeSpec.Float => nameof(ConfigEntryTypeSpec.Float),
            ConfigEntryTypeSpec.Double => nameof(ConfigEntryTypeSpec.Double),
            ConfigEntryTypeSpec.String => nameof(ConfigEntryTypeSpec.String),
            ConfigEntryTypeSpec.Nested => nameof(ConfigEntryTypeSpec.Nested),
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    private static void ValidateSpec(ConfigDefinitionSpec? spec)
    {
        ThrowIf(() => spec is null);

        ThrowIf(() => spec!.RootConfigs.IsDefaultOrEmpty);
        foreach (var rootConfigSpec in spec!.RootConfigs)
        {
            ValidateSpec(rootConfigSpec);
        }

        if (spec.Configs is null)
        {
            return;
        }

        foreach (var configSpec in spec.Configs)
        {
            ValidateSpec(configSpec);
        }
    }

    private static void ValidateSpec(RootConfigSpec? spec)
    {
        ThrowIf(() => spec is null);

        ThrowIf(() => string.IsNullOrWhiteSpace(spec!.Version));

        ValidateSpec(spec as ConfigSpec);
    }

    private static void ValidateSpec(ConfigSpec? spec)
    {
        ThrowIf(() => spec is null);

        ThrowIf(() => string.IsNullOrWhiteSpace(spec!.ClassName));
        ThrowIf(() => string.IsNullOrWhiteSpace(spec!.ClassNamespace));

        ThrowIf(() => spec!.Entries.IsDefaultOrEmpty);
        foreach (var configEntrySpec in spec!.Entries)
        {
            ValidateSpec(configEntrySpec);
        }
    }

    private static void ValidateSpec(ConfigEntrySpec? spec)
    {
        ThrowIf(() => spec is null);

        ThrowIf(() => string.IsNullOrWhiteSpace(spec!.Name));
    }

    private static void ThrowIf(Func<bool> predicate)
    {
        if (predicate.Invoke())
        {
            throw new InvalidOperationException();
        }
    }
}
