when:
  - event: push
    branch: main

matrix:
  PROJECT:
    - Common.Mod
    - Common.Mod.Generator

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - bash build.sh -t Build --project ${PROJECT}
