when:
  - event: push
    branch: main

matrix:
  PROJECT:
    - Common.Mod
    - Common.Mod.Generator

steps:
  - name: bootstrap
    image: git.omni.ms/omnilium/toolbox:latest
    environment:
      COPYPARTY_USER:
        from_secret: copyparty_user
      COPYPARTY_PASSWORD:
        from_secret: copyparty_password
    commands:
      - bash .woodpecker/fetch-deps.sh $${COPYPARTY_USER} $${COPYPARTY_PASSWORD}
      - bash bootstrap.sh

  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - bash build.sh -t Build --project ${PROJECT}
