when:
  - event: push
    branch: main

matrix:
  PROJECT:
    - Common.Mod
    - Common.Mod.Generator

steps:
  - name: bootstrap
    image: git.omni.ms/omnilium/toolbox:latest
    environment:
      COPYPARTY_USER:
        from_secret: copyparty_user
      COPYPARTY_PASSWORD:
        from_secret: copyparty_password
    commands:
      - bash scripts/fetch-game.sh $${COPYPARTY_USER} $${COPYPARTY_PASSWORD}
      - bash scripts/bootstrap.sh

  - name: build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - bash build.sh --target Build --oproject ${PROJECT} --oversion 12.34.56
