when:
  - event: tag

depends_on:
  - build-mod
  - test-mod

matrix:
  PROJECT:
    - Common.Mod
    - Common.Mod.Common
    - Common.Mod.Generator

steps:
  - name: bootstrap
    image: git.omni.ms/omnilium/toolbox:latest
    pull: true
    environment:
      REMOTE_USERNAME:
        from_secret: copyparty_user
      REMOTE_PASSWORD:
        from_secret: copyparty_password
    commands:
      - bash bootstrap.sh remote

  - name: package
    image: mcr.microsoft.com/dotnet/sdk:9.0
    pull: true
    commands:
      - bash build.sh --target Package --general-project ${PROJECT} --general-version ${CI_COMMIT_TAG}

  - name: publish
    image: mcr.microsoft.com/dotnet/sdk:9.0
    pull: true
    environment:
      NUGET_REGISTRY_URL: https://git.omni.ms/api/packages/vintage-story-mods/nuget/index.json
      NUGET_REGISTRY_USERNAME:
        from_secret: nuget_registry_username
      NUGET_REGISTRY_PASSWORD:
        from_secret: nuget_registry_password
    commands:
      - dotnet nuget update source forgejo --username $${NUGET_REGISTRY_USERNAME} --password $${NUGET_REGISTRY_PASSWORD} --store-password-in-clear-text
      - dotnet nuget push --source forgejo out/*.nupkg
