when:
  - event: tag

steps:
  - name: bootstrap
    image: git.omni.ms/omnilium/node:latest
    pull: true
    directory: docs
    commands:
      - pnpm install --frozen-lockfile

  - name: build
    image: git.omni.ms/omnilium/node:latest
    pull: true
    directory: docs
    commands:
      - pnpm build

  - name: archive
    image: git.omni.ms/omnilium/toolbox:latest
    pull: true
    directory: docs/dist
    commands:
      - zip -r website_${CI_COMMIT_TAG}.zip .

  - name: release
    image: woodpeckerci/plugin-release:latest
    pull: true
    directory: docs
    settings:
      api-key:
        from_secret: forgejo_release_key
      files:
        - dist/*.zip
      draft: true
