on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - Common.Mod
          - Common.Mod.Common
          - Common.Mod.Generator
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET SDK 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies from cache
        uses: actions/cache@v5
        with:
          key: deps-${{ hashFiles('bootstrap.sh') }}
          path: |
            vendor/vs.tar.gz
            vendor/*.zip
      - name: Bootstrap
        run: bash bootstrap.sh
      - name: Build
        run: bash build.sh --target Build --general-project ${{ matrix.project }}
